*** Variables ***
${elem_appointment_conf_title}=          //*[contains(text(),'Appointment Confirmation')]

${elem_facility_selected} =              //p[@id='facility']
${elem_readmission_selected} =           //p[@id='hospital_readmission']
${elem_healthcare_program_selected} =    //p[@id='program']
${elem_visit_date_selected} =            //p[@id='visit_date']
${elem_comment_selected} =               //p[@id='comment']

${elem_go_to_homepage_btn}=              //*[@class='btn btn-default']