*** Variables ***
# Button locators
${elem_make_appointment} =    //a[@id='btn-make-appointment']


# Menu locators
${elem_menu_toggle} =    //a[@id='menu-toggle']
${elem_home_item} =      //a[@href='./' and text()='Home']
${elem_login_item} =     //a[@href='profile.php#login']
${elem_history_item} =   //a[@href='history.php#history']
${elem_profile_item} =   //a[@href='profile.php#profile']
${elem_logout_item} =    //a[@href='authenticate.php?logout']
